### Create an new user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Julia",
  "email": "julia@example.com",
  "password": "@123412"
}
### Get user profile
GET http://localhost:3333/users/profile/1aba335f-526f-47c5-b8ae-2dcd9f29ad2b HTTP/1.1
